import { MenuItem } from "./types";

// Array of Objects bertipe MenuItem
export const menuItems: MenuItem[] = [
  {
    id: "M01",
    name: "Nasi Goreng Mercon",
    price: 25000,
    category: "food",
    description:
      "Nasi goreng pedas gila dengan telur mata sapi dan ayam suwir.",
    image: "https://picsum.photos/200?random=1",
    isVegan: false,
    isSpicy: true,
    rating: 4.8,
  },
  {
    id: "M02",
    name: "Salad Buah Segar",
    price: 18000,
    category: "dessert",
    description: "Potongan buah segar apel, anggur, dan mangga dengan mayones.",
    image: "https://picsum.photos/200?random=2",
    isVegan: true,
    isSpicy: false,
    rating: 4.5,
  },
  {
    id: "M03",
    name: "Es Kopi Susu Aren",
    price: 15000,
    category: "drink",
    description: "Kopi espresso dengan susu segar dan gula aren asli.",
    image: "https://picsum.photos/200?random=3",
    isVegan: false,
    isSpicy: false,
  },
  {
    id: "M04",
    name: "Tahu Walik Crispy",
    price: 12000,
    category: "snack",
    description:
      "Tahu goreng krispi dengan isian aci gurih, disajikan dengan petis.",
    image: "https://picsum.photos/200?random=4",
    isVegan: true,
    isSpicy: false,
    rating: 4.2,
  },
  {
    id: "M05",
    name: "Mie Kuah Tomyum",
    price: 28000,
    category: "food",
    description: "Mie kuah asam pedas ala Thai dengan udang dan jamur.",
    image: "https://picsum.photos/200?random=5",
    isVegan: false,
    isSpicy: true,
    rating: 4.9,
  },
  {
    id: "M06",
    name: "Matcha Latte",
    price: 18000,
    category: "drink",
    description: "Minuman teh hijau Jepang dipadukan dengan susu.",
    image: "https://picsum.photos/200?random=6",
    isVegan: true,
    isSpicy: false,
  },
  {
    id: "M07",
    name: "Pisang Coklat Lumer",
    price: 10000,
    category: "snack",
    description: "Lumpia pisang berisi coklat lumer saat digigit.",
    image: "https://picsum.photos/200?random=7",
    isVegan: true,
    isSpicy: false,
    rating: 4.7,
  },
  {
    id: "M08",
    name: "Pudding Karamel",
    price: 15000,
    category: "dessert",
    description: "Pudding susu lembut berbalut saus karamel manis.",
    image: "https://picsum.photos/200?random=8",
    isVegan: false,
    isSpicy: false,
  },
];
