import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  mainContainer: { flex: 1, backgroundColor: "#f8fafc", paddingTop: 50 },
  header: { paddingHorizontal: 20, marginBottom: 15 },
  headerTitle: { fontSize: 24, fontWeight: "bold", color: "#0f172a" },
  headerSubtitle: { fontSize: 14, color: "#64748b" },
  searchContainer: { paddingHorizontal: 20, marginBottom: 15 },
  searchInput: { backgroundColor: "#ffffff", borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 12, paddingHorizontal: 15, paddingVertical: 10, fontSize: 14 },
  categoryContainer: { paddingLeft: 20, marginBottom: 15 },
  categoryChip: { backgroundColor: "#2563eb", paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, marginRight: 10 },
  categoryText: { color: "#ffffff", fontWeight: "600", fontSize: 12 },
  listContainer: { paddingHorizontal: 20, paddingBottom: 20 },
  cardContainer: { backgroundColor: "#ffffff", borderRadius: 16, marginBottom: 15, overflow: "hidden", elevation: 3, shadowColor: "#000", shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
  cardImage: { width: "100%", height: 140, backgroundColor: "#e2e8f0" },
  cardContent: { padding: 15 },
  cardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 6 },
  cardTitle: { fontSize: 16, fontWeight: "bold", color: "#1e293b" },
  cardDescription: { fontSize: 12, color: "#64748b", marginBottom: 12 },
  cardFooter: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  cardPrice: { fontSize: 15, fontWeight: "bold", color: "#2563eb" },
  addButton: { backgroundColor: "#2563eb", paddingHorizontal: 16, paddingVertical: 8, borderRadius: 8 },
  addButtonText: { color: "#ffffff", fontWeight: "bold", fontSize: 12 },
  badge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, alignSelf: "flex-start" },
  badgeText: { color: "#ffffff", fontSize: 10, fontWeight: "bold" },
  summaryContainer: { backgroundColor: "#ffffff", borderTopWidth: 1, borderColor: "#e2e8f0", padding: 20, borderTopLeftRadius: 20, borderTopRightRadius: 20, elevation: 10 },
  summaryItemRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 8 },
  summaryTotalRow: { flexDirection: "row", justifyContent: "space-between", marginTop: 10, paddingTop: 10, borderTopWidth: 1, borderColor: "#f1f5f9" },
  summaryTotalText: { fontSize: 16, fontWeight: "bold", color: "#0f172a" },
  checkoutButton: { backgroundColor: "#0f172a", paddingVertical: 12, borderRadius: 12, marginTop: 12, alignItems: "center" },
  checkoutText: { color: "#ffffff", fontWeight: "bold", fontSize: 14 },
  qtyBtn: { backgroundColor: "#ef4444", width: 24, height: 24, borderRadius: 12, alignItems: "center", justifyContent: "center" },
  qtyBtnText: { color: "#ffffff", fontWeight: "bold", fontSize: 14, lineHeight: 18 },

  // --- STYLE BARU UNTUK MODAL STRUK ---
  modalOverlay: { flex: 1, backgroundColor: "rgba(0, 0, 0, 0.5)", justifyContent: "center", alignItems: "center" },
  receiptContainer: { width: "85%", backgroundColor: "#ffffff", borderRadius: 16, padding: 25, elevation: 5 },
  receiptHeader: { fontSize: 22, fontWeight: "bold", textAlign: "center", color: "#0f172a", marginBottom: 5 },
  receiptDate: { textAlign: "center", color: "#64748b", fontSize: 12, marginBottom: 15 },
  receiptDivider: { borderWidth: 1, borderColor: "#cbd5e1", borderStyle: "dashed", marginVertical: 15 },
  receiptItemText: { fontSize: 14, color: "#334155" },
  receiptTotalText: { fontSize: 18, fontWeight: "bold", color: "#059669" },
  receiptFooter: { textAlign: "center", color: "#64748b", fontSize: 12, marginTop: 20, fontStyle: "italic" },
  doneButton: { backgroundColor: "#059669", paddingVertical: 12, borderRadius: 12, marginTop: 20, alignItems: "center" },
  doneButtonText: { color: "#ffffff", fontWeight: "bold", fontSize: 14 }
});